#!/bin/bash

if [ "$1" != "reallydoit" ]
then
  echo $0: doing nothing because the magic sauce wasn\'t provided ('reallydoit')
else
  echo $0: deleting the file state cache -- will need to restart initial backup!

  CACHEPATH=/var/DQD.RealTimeBackup/FileStateCache

  if [ -d $CACHEPATH ]
  then
    echo -d says go
    du --total $CACHEPATH
    rm -r $CACHEPATH
  else
    echo Nothing to clean up.
  fi
fi
